// @ts-check
import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// The viewer as a static site: web/ plus the library sources, no bundling. It is
// served by GitHub Pages and packaged for `wireskein gui` (the Python package
// ships this directory from the npm tarball).
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const site = join(root, 'site');
rmSync(site, { recursive: true, force: true });
mkdirSync(site, { recursive: true });
cpSync(join(root, 'web'), site, { recursive: true });
cpSync(join(root, 'src'), join(site, 'src'), { recursive: true });
writeFileSync(join(site, 'wireskein-web.js'), ['// Generated by scripts/build-site.js.', "export * from './src/index.js';", ''].join('\n'));
writeFileSync(join(site, '.nojekyll'), '');
console.log('site/ ready');
